export { Overview as PaidOverviewTab }    from './OverviewTab'
export { Spend as PaidSpendTab }       from './SpendTab'
export { Quality as PaidQualityTab }     from './QualityTab'
export { Competition as PaidCompetitionTab } from './CompetitionTab'
export { Actions as PaidActionsTab }     from './ActionsTab'
