export { Overview as AiOverviewTab }     from './OverviewTab'
export { Crawlability as AiCrawlabilityTab } from './CrawlabilityTab'
export { Citations as AiCitationsTab }    from './CitationsTab'
export { Entities as AiEntitiesTab }     from './EntitiesTab'
export { Schema as AiSchemaTab }       from './SchemaTab'
