export { Overview as CompOverviewTab }    from './OverviewTab'
export { MarketShare as CompMarketShareTab } from './MarketShareTab'
export { Backlinks as CompBacklinksTab }   from './BacklinksTab'
export { Content as CompContentTab }     from './ContentTab'
export { Actions as CompActionsTab }     from './ActionsTab'
