export { FullOverviewTab } from './OverviewTab'
export { FullTechTab }     from './TechTab'
export { FullContentTab }  from './ContentTab'
export { FullLinksTab }    from './LinksTab'
export { FullActionsTab }  from './ActionsTab'
