export { Overview as CommerceOverviewTab }  from './OverviewTab'
export { Inventory as CommerceInventoryTab } from './InventoryTab'
export { Schema as CommerceSchemaTab }    from './SchemaTab'
export { Feed as CommerceFeedTab }      from './FeedTab'
export { Funnel as CommerceFunnelTab }    from './FunnelTab'
