export const CMS_KEYS = [
  'wordpress',
  'shopify',
  'wix',
  'squarespace',
  'hubspot-cms',
  'ghost',
  'medium',
  'substack',
  'magento',
  'webflow',
  'framer',
  'drupal',
  'joomla',
  'bigcommerce',
  'salesforce-commerce',
  'woocommerce',
  'bitrix',
  'duda',
  'intercom',
  'astro',
  'jekyll',
  'hugo',
  'notion',
  'contentful',
  'sanity',
  'strapi',
  'nextjs-headless',
  'gatsby',
  'custom',
] as const;

export type CmsKey = typeof CMS_KEYS[number];

export const CMS_LABELS: Record<CmsKey, string> = {
  wordpress: 'WordPress',
  shopify: 'Shopify',
  wix: 'Wix',
  squarespace: 'Squarespace',
  'hubspot-cms': 'HubSpot CMS',
  ghost: 'Ghost',
  medium: 'Medium',
  substack: 'Substack',
  magento: 'Magento',
  webflow: 'Webflow',
  framer: 'Framer',
  drupal: 'Drupal',
  joomla: 'Joomla',
  bigcommerce: 'BigCommerce',
  'salesforce-commerce': 'Salesforce Commerce',
  woocommerce: 'WooCommerce',
  bitrix: 'Bitrix',
  duda: 'Duda',
  intercom: 'Intercom',
  astro: 'Astro',
  jekyll: 'Jekyll',
  hugo: 'Hugo',
  notion: 'Notion',
  contentful: 'Contentful',
  sanity: 'Sanity',
  strapi: 'Strapi',
  'nextjs-headless': 'Next.js (headless)',
  gatsby: 'Gatsby',
  custom: 'Custom',
};
